### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Switched to AsyncKeyedLock which is able to clean up the dictionary for single threaded scopes.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@ahmadakra @mohamadakra

**Comment by MarkCiliaVincenti** [comment]
@ahmadakra @mohamadakra

**Comment by MarkCiliaVincenti** [comment]
@ahmadakra @mohamadakra

**Comment by MarkCiliaVincenti** [comment]
@ahmadakra @mohamadakra ?

**Comment by MarkCiliaVincenti** [comment]
@mohamadakra

**Comment by MarkCiliaVincenti** [comment]
@ahmadakra @mohamadakra

**Comment by mohamadakra** [comment]
For ease of maintenance and distribution we prefer to limit the number of dependencies in the Client library.

**Comment by MarkCiliaVincenti** [comment]
> For ease of maintenance and distribution we prefer to limit the number of dependencies in the Client library.


OK. However are you aware of the small memory leak if you keep using different keys? (not sure exactly how this is used, so it may or may not be an issue)

**Comment by mohamadakra** [comment]
At the moment, this utility class is only used in one place and with a single hardcoded key, so it won't cause a memory leak. However, you thankfully brought to our attention how it could cause a memory leak if its usage is expanded in the future, so we will get it fixed

**Comment by MarkCiliaVincenti** [comment]
> At the moment, this utility class is only used in one place and with a single hardcoded key, so it won't cause a memory leak. However, you thankfully brought to our attention how it could cause a memory leak if its usage is expanded in the future, so we will get it fixed


Careful with the race conditions. They can get quite tricky.

**Pull request closed without merging**
